name: Android Apk - Build & Release

on: [push]

jobs:
    build:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v1

            - name: Set up JDK 11.0.7
              uses: actions/setup-java@v1
              with:
                  java-version: '11.0.7'

            - name: Use Node.js 14.11.0
              uses: actions/setup-node@v1
              with:
                  node-version: '14.11.0'

            - name: Yarn Install, Build, (Test)
              run: |
                  sh prepare_beta.sh
                  yarn install --frozen-lockfile
                  yarn build
                  yarn bundle

            - name: Upload APK artifact
              uses: actions/upload-artifact@v1
              with:
                  name: app-signed-release.apk
                  path: android/app/build/outputs/apk/signed/release/app-signed-release.apk

            - name: Publish Apk to Github Release
              uses: marvinpinto/action-automatic-releases@latest
              if: github.ref == 'refs/heads/master'
              with:
                  files: android/app/build/outputs/apk/signed/release/app-signed-release.apk
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  automatic_release_tag: 'latest'
                  title: 'Nepaltoday - Beta Build'
                  prerelease: false

            - name: Publish Android Bundle to Google Play Store
              uses: r0adkll/upload-google-play@v1
              if: github.ref == 'refs/heads/master'
              with:
                  serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON_PLAIN_TEXT }}
                  packageName: 'com.siristechnology.nepaltodayapp.beta'
                  releaseFile: android/app/build/outputs/bundle/signedRelease/app-signed-release.aab
                  track: production
